In [5]:
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("netflix_titles.csv")
df.head()

Saving netflix_titles.csv to netflix_titles (2).csv

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

How many rows and columns are contained in the dataset?

In [7]:
df.shape

(8807, 12)

What datatypes are contained in the dataset?

In [9]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

Is the dataset complete? i.e no missing values?

In [10]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

List the number of Movies and TV Shows among the last 20 rows
of the dataset

In [13]:
df.tail(20)[['title', 'type']]

                              title     type
8787      You Can’t Fight Christmas    Movie
8788                   You Carry Me    Movie
8789            You Changed My Life    Movie
8790  You Don't Mess with the Zohan    Movie
8791                    Young Adult    Movie
8792                    Young Tiger    Movie
8793           Yours, Mine and Ours    Movie
8794                         اشتباك    Movie
8795                Yu-Gi-Oh! Arc-V  TV Show
8796                     Yunus Emre  TV Show
8797                      Zak Storm  TV Show
8798                       Zed Plus    Movie
8799                          Zenda    Movie
8800             Zindagi Gulzar Hai  TV Show
8801                        Zinzana    Movie
8802                         Zodiac    Movie
8803                    Zombie Dumb  TV Show
8804                     Zombieland    Movie
8805                           Zoom    Movie
8806                         Zubaan    Movie